name: NTIRCommunity
version: '${project.version}'
main: me.aq.plugin.ntirEco.NTIReco
api-version: 1.18
commands:
  points:
    description: 查看點數
    usage: /<command>
  pointsadmin:
    description: 管理點數
    usage: /<command>
  shop:
    description: 開啟官方商城選單
    usage: /<command>
  setprefix:
    usage:
    description: 設定稱號
  createcommunity:
    usage:
    description:
    aliases: cc
  setcommunity:
    usage:
    description:
  tempban:
    usage:
    description: