name: NTIRCommunity
version: '${project.version}'
main: me.aq.plugin.ntirEco.NTIReco
api-version: 1.18
commands:
  points:
    description:
    usage:
  pointsadmin:
    description:
    usage:
  shop:
    description:
    usage:
  setprefix:
    usage:
    description:
  verify:
    usage:
    description:
  tempban:
    usage:
    description:
  unban:
    usage:
    description:
  pvp:
    usage:
    description:
  getitem:
    usage:
    description:
  bann:
    usage:
    description:

  #cjoin:
    #description:
    #usage:
  #allow:
    #description:
    #usage:
  #createcommunity:
    #usage:
    #description:
    #aliases: cc
  #setcommunity:
    #usage:
    #description: