name: NTIRCommunity
version: '${project.version}'
main: me.aq.plugin.ntirEco.NTIReco
api-version: 1.18
commands:
  points:
    description:
    usage:
  pointsadmin:
    description:
    usage:
  shop:
    description:
    usage:
  setprefix:
    usage:
    description:
  createcommunity:
    usage:
    description:
    aliases: cc
  setcommunity:
    usage:
    description:
  verify:
    usage:
    description:
  msg:
    usage:
    description:
    aliases: m
  tempban:
    usage:
    description:
  unban:
    usage:
    description: